

# CONFIGURACION DEL REGISTRO DE ACCESO A DATOS DE NIVEL ALTO
log4j.logger.es.sdweb.application.componentes.util.logging.AccesoDatos=DEBUG, AccesoDatos
log4j.additivity.es.sdweb.application.componentes.util.logging.AccesoDatos=false

log4j.appender.AccesoDatos=es.sdweb.application.componentes.util.logging.SdwebRollingFileAppender


log4j.appender.AccesoDatos.DatePattern='_'yyMMdd
log4j.appender.AccesoDatos.File=${catalina.base}/logs/MemoryCorp/RA_PL_MemoryCorp.log
log4j.appender.AccesoDatos.layout=org.apache.log4j.PatternLayout
log4j.appender.AccesoDatos.layout.ConversionPattern=%m
log4j.appender.AccesoDatos.Threshold=DEBUG
log4j.appender.AccesoDatos.MaxFileSize=500KB
log4j.appender.AccesoDatos.MaxBackupIndex=99


# CONFIGURACION DEL REGISTRO DE TRAZAS
log4j.logger.es.sdweb.application.componentes.util.logging.LogicaNegocio=DEBUG, LogicaNegocio
log4j.additivity.es.sdweb.application.componentes.util.logging.LogicaNegocio=false

log4j.appender.LogicaNegocio=es.sdweb.application.componentes.util.logging.SdwebRollingFileAppender
log4j.appender.LogicaNegocio.DatePattern='_'yyMMdd
log4j.appender.LogicaNegocio.File=${catalina.base}/logs/MemoryCorp/RT_PL_MemoryCorp.log
log4j.appender.LogicaNegocio.layout=org.apache.log4j.PatternLayout
log4j.appender.LogicaNegocio.layout.ConversionPattern=[%d] %m%n
log4j.appender.LogicaNegocio.Threshold=DEBUG
log4j.appender.LogicaNegocio.MaxFileSize=128MB
log4j.appender.LogicaNegocio.MaxBackupIndex=999


# CONFIGURACION DEL REGISTRO DE ERRORES
log4j.logger.es.sdweb.application.componentes.util.logging.Errores=DEBUG,console,Errores

log4j.appender.Errores=es.sdweb.application.componentes.util.logging.SdwebRollingFileAppender
log4j.appender.Errores.DatePattern='_'yyMM
log4j.appender.Errores.File=${catalina.base}/logs/MemoryCorp/RE_PL_MemoryCorp.log
log4j.appender.Errores.layout=org.apache.log4j.PatternLayout
log4j.appender.Errores.layout.ConversionPattern=%m
log4j.appender.Errores.Threshold=DEBUG

# Registro en consola
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%m
log4j.appender.console.Threshold=DEBUG