package es.sdweb.application.controller;

import es.sdweb.application.componentes.util.FileUtil;
import java.io.InputStream;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;

import org.apache.struts.action.ActionServlet;
import es.sdweb.application.util.GestorParametrosConfiguracion;
import es.sdweb.application.componentes.util.logging.Log;

/**
 * @author Antonio Carro Mariño
 *
 *         Este Servlet se encargara de ordenar la carga de los parametros de
 *         configuracion de Web.xml y applicationConfig.xml
 */
public class ApplicationActionServlet extends ActionServlet {

	/**
	 * Autogenerated Serial Version UID
	 */
	private static final long serialVersionUID = 2919379848033053512L;

	// PARAMETROS REQUERIDOS PARA LA INICIALIZACIÓN DEL GESTOR PARÁMETROS CONFIGURACIÓN
	private static final String FICHERO_CONFIGURACION_NAME = "Configuracion/applicationConfig.xml"; // Nombre del archivo de configuración

	// PARAMETROS REQUERIDOS PARA LA INICIALIZACIÓN DEL REGISTRO DE LOGS
	private static final String FICHERO_LOGS_NAME = "log4j.properties";
	private static final String PARAM_APP_NAME = "application.name";
	private static final String PARAM_APP_VERSION = "application.version";

	@Override
	public void init(ServletConfig sc) {
		// Inicializamos el estado de la superclase
		try {
			super.init(sc);
		} catch (ServletException e) {
			e.printStackTrace(System.err);
		}

		System.out.println("ApplicationActionServlet.init(): INICIALIZANDO EL SERVLET ...");

		// Indicamos al GestorParametrosConfiguracion el inputStream anterior
		System.out.println("ApplicationActionServlet.init(): Inicializando el gestor de parametros de configuracion ...");

		InputStream configuracion = sc.getServletContext().getResourceAsStream(FICHERO_CONFIGURACION_NAME);
		GestorParametrosConfiguracion.loadFromXML(configuracion);
		System.out.println("ApplicationActionServlet.init(): [OK] Parametros de configuracion cargados.");

		// Comprobamos que la ruta al fichero 'key.properties' esta correctamente configurada
		String rijndaelPasswordFilePath = GestorParametrosConfiguracion.getParametro("rijndael.password.properties.file.path");
		System.out.println("ApplicationActionServlet.init(): Comprobamos que la ruta al fichero '" + rijndaelPasswordFilePath + "' esta correctamente configurada...");
		InputStream is = FileUtil.openFile(rijndaelPasswordFilePath);

		if (is == null) {
			System.err.println("ApplicationActionServlet.init(): [ERROR] No se encuentra el fichero '" + rijndaelPasswordFilePath + "'. Compruebe que la ruta del fichero es correcta.");
		} else {
			FileUtil.closeFile(is);
			System.err.println("ApplicationActionServlet.init(): [OK] Fichero '" + rijndaelPasswordFilePath + "' localizado.");
		}

		// Recuperamos el InputStream necesario para leer los datos del fichero log4j.properties
		InputStream logConf = sc.getServletContext().getResourceAsStream("Configuracion/" + FICHERO_LOGS_NAME);
		System.out.println("ApplicationActionServlet.init(): [OK] Cargado fichero log4j.properties.");

		// Inicializacion del servicio de log
		String appName = GestorParametrosConfiguracion.getParametro(PARAM_APP_NAME);
		String appVersion = GestorParametrosConfiguracion.getParametro(PARAM_APP_VERSION);

		System.out.println("ApplicationActionServlet.init(): Inicializando los ficheros de logs de la aplicacion ...");
		Log.init(logConf, appName, appVersion); // Inicializacion
		FileUtil.closeFile(logConf); // Cerramos el fichero
		System.out.println("ApplicationActionServlet.init(): [OK] ficheros de logs inicializados.");
		System.out.println("ApplicationActionServlet.init(): [OK] Fin de la INICIALIZACION DE LA APLICACION (del ActionServlet de Struts 1.3.10).");

		Log.logRT("-------------------------------------------------------------------------------------------------------------");
		Log.logRT("ApplicationActionServlet.init(): [OK] Fin de la INICIALIZACION DE LA APLICACION (del ActionServlet de Struts 1.3.10).");
		Log.logRT("");
	}
} // Class